### PR TITLE
#160833477 Implement PEP8 standards 

### PR DESCRIPTION
**Pull request by d-rita**
**What does this PR do?**
- Implement PEP8 standards within the python code. 

**Description of tasks**
- Trim trailing whitespace
- Implement UPPER_CASE for global variables. 
- Implement snake_case convention. 

**How can this be manually tested?**
- In the terminal, run  `pylint tests/test.py` to check the test file. 
- In the terminal, run  `pylint app/models/orders.py` to check the orders file. 
- - In the terminal, run  `pylint app/views/views.py` to check the views file. 

**Relevant Pivotal Tracker Story**
- #160833477

### CODE REVIEW

**Comment by aayebare** [comment]
I'm proud ..nice progress though some of your commit messages are like mine at https://github.com/m-asiimwe/Fast-Food-Fast/pull/4#issue-218626395 before you came through..Great work though 100%

**Comment by aayebare** [comment]
I was also told that it's not necessary to add screen shots of code. Since we can already review it from the repo

**Comment by d-rita** [comment]
Okay. Will do.

**Comment by kdaglas** [comment]
Good commit messages... though some recommended convention needed

**Pull request merged**
